#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.1.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Jun 18 14:59:05 +06 2024
# SW Build 3900603 on Fri Jun 16 19:30:25 MDT 2023
#
# IP Build 3900379 on Sat Jun 17 05:28:05 MDT 2023
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim top_behav -key {Behavioral:sim_1:Functional:top} -tclbatch top.tcl -protoinst "protoinst_files/bd_b3b8.protoinst" -protoinst "protoinst_files/design_bd.protoinst" -view /home/symon/hpi-dev/hpi-vivado-project-dev/vivado_design_192b/top_behav.wcfg -log simulate.log"
xsim top_behav -key {Behavioral:sim_1:Functional:top} -tclbatch top.tcl -protoinst "protoinst_files/bd_b3b8.protoinst" -protoinst "protoinst_files/design_bd.protoinst" -view /home/symon/hpi-dev/hpi-vivado-project-dev/vivado_design_192b/top_behav.wcfg -log simulate.log

